---

- name: django-manage | Run manage commands
  django_manage:
      command={{item}}
      app_path={{django_src_dir}}/{{base_project_name}}
      settings={{django_settings_module}}
      virtualenv={{django_env_dir}}
  with_items: django_manage_list
  ignore_errors: django_ignore_errors
